"""empty message

Revision ID: 00d722d284f8
Revises: 
Create Date: 2023-11-30 18:03:55.271114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d722d284f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_creator',
               existing_type=sa.TEXT(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text("'False'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_creator',
               existing_type=sa.Boolean(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'False'"))

    # ### end Alembic commands ###
